### ISSUE TITLE
Add "delete-all" command 

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-liquibase#15]
Often the dev workflow requires wiping out the schema and starting with migrations from scratch. Liquibase standard "delete-all" command should come handy.

**Comment by ebondareva** [comment]
The command has been named "--lb-drop-all" because of original [LQ maven goal name](http://www.liquibase.org/documentation/maven/maven_dropall.html) and LQ API.
The command has been extended with CLI options "--schema" and "--catalog".
