### ISSUE TITLE
Add Liquibase context to control which changeSets will be executed in migration run

### ISSUE THREAD

**Issue by ebondareva** [bootique/bootique-liquibase#18]
Presumable solution is passing command-line value "context" contributed to Bootique as an option.

**Comment by andrus** [comment]
Let's define the details, such as option name. Also see #16.

**Comment by ebondareva** [comment]
Cli option "lb-context" has been introduced.

**Comment by ebondareva** [comment]
Changed short name to "-x". Added possibility to specify CLI flag multiple times.
To sum it up, a set of contexts can be provided:
1. -x=test,prod
2. -x=test -x=prod
